"""rename_models

Revision ID: 9d908d735837
Revises: 5a10ffca5700
Create Date: 2024-11-18 20:34:52.837421

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d908d735837"
down_revision = "5a10ffca5700"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servicebinstitution",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "servicebstudent",
        sa.Column("name", sa.String(length=63), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["servicebinstitution.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_servicebstudent_institution_id"),
        "servicebstudent",
        ["institution_id"],
        unique=False,
    )
    op.drop_table("institution")
    op.drop_index("ix_student_institution_id", table_name="student")
    op.drop_table("student")
    op.drop_table("fdwdemo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fdwdemo",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="fdwdemo_pkey"),
    )
    op.create_table(
        "student",
        sa.Column("name", sa.VARCHAR(length=63), autoincrement=False, nullable=False),
        sa.Column("institution_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institution.id"], name="student_institution_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="student_pkey"),
    )
    op.create_index(
        "ix_student_institution_id", "student", ["institution_id"], unique=False
    )
    op.create_table(
        "institution",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="institution_pkey"),
    )
    op.drop_index(
        op.f("ix_servicebstudent_institution_id"), table_name="servicebstudent"
    )
    op.drop_table("servicebstudent")
    op.drop_table("servicebinstitution")
    # ### end Alembic commands ###
