"""add_index_on_fk

Revision ID: 985c1829fa29
Revises: 6ce86e8beca5
Create Date: 2024-11-14 19:39:54.593993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985c1829fa29'
down_revision = '6ce86e8beca5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_student_institution_id'), 'student', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_institution_id'), table_name='student')
    # ### end Alembic commands ###
